<a href="https://colab.research.google.com/github/Hitesh123mori/R-squared---MachineLearning/blob/main/ModelSelection_MultipleRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from numpy import set_printoptions

In [2]:
df = pd.read_csv("RegressionData.csv")

In [3]:
df.head(5)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
X =  df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2 , random_state = 0)

In [6]:
X_train

array([[  11.22,   43.13, 1017.24,   80.9 ],
       [  13.67,   54.3 , 1015.92,   75.42],
       [  32.84,   77.95, 1014.68,   45.8 ],
       ...,
       [  16.81,   38.52, 1018.26,   75.21],
       [  12.8 ,   41.16, 1022.43,   86.19],
       [  32.32,   67.9 , 1006.08,   37.93]])

In [7]:
X_test

array([[  28.66,   77.95, 1009.56,   69.07],
       [  17.48,   49.39, 1021.51,   84.53],
       [  14.86,   43.14, 1019.21,   99.14],
       ...,
       [  12.24,   44.92, 1023.74,   88.21],
       [  27.28,   47.93, 1003.46,   59.22],
       [  17.28,   39.99, 1007.09,   74.25]])

In [8]:
y_train

array([473.93, 467.87, 431.97, ..., 459.01, 462.72, 428.12])

In [9]:
y_test

array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

In [10]:
mul_reg = LinearRegression()
mul_reg.fit(X_train,y_train)

LinearRegression()

In [11]:
y_pred1 = mul_reg.predict(X_test)
np.set_printoptions(precision=1)

In [12]:
r2_score(y_test,y_pred1)

0.9325315554761303