<a href="https://colab.research.google.com/github/Hitesh123mori/R-squared---MachineLearning/blob/main/ModelSelection_SVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [265]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from numpy import set_printoptions
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

In [266]:
df = pd.read_csv("RegressionData.csv")

In [267]:
df.head(5)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [268]:
X =  df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [269]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2 , random_state = 0)

In [270]:
X_train

array([[  11.22,   43.13, 1017.24,   80.9 ],
       [  13.67,   54.3 , 1015.92,   75.42],
       [  32.84,   77.95, 1014.68,   45.8 ],
       ...,
       [  16.81,   38.52, 1018.26,   75.21],
       [  12.8 ,   41.16, 1022.43,   86.19],
       [  32.32,   67.9 , 1006.08,   37.93]])

In [271]:
X_test

array([[  28.66,   77.95, 1009.56,   69.07],
       [  17.48,   49.39, 1021.51,   84.53],
       [  14.86,   43.14, 1019.21,   99.14],
       ...,
       [  12.24,   44.92, 1023.74,   88.21],
       [  27.28,   47.93, 1003.46,   59.22],
       [  17.28,   39.99, 1007.09,   74.25]])

In [272]:
y_train

array([473.93, 467.87, 431.97, ..., 459.01, 462.72, 428.12])

In [273]:
y_test

array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

In [274]:
sc_x = StandardScaler()
X_train  = sc_x.fit_transform(X_train)
sc_y = StandardScaler()
y_train  = sc_y.fit_transform(y_train.reshape(len(y_train),1))

In [275]:
regressor = SVR(kernel='rbf')

In [276]:
X_train

array([[-1.13572795, -0.88685592,  0.67357894,  0.52070558],
       [-0.80630243, -0.00971567,  0.45145467,  0.14531044],
       [ 1.77128416,  1.84743445,  0.24279248, -1.88374143],
       ...,
       [-0.38409993, -1.24886277,  0.84522042,  0.13092486],
       [-0.9232821 , -1.04155299,  1.54693117,  0.8830852 ],
       [ 1.70136528,  1.05824381, -1.20438076, -2.42285818]])

In [277]:
y_train

array([[ 1.15069786],
       [ 0.79540777],
       [-1.30936356],
       ...,
       [ 0.27595724],
       [ 0.49346982],
       [-1.53508417]])

In [278]:
regressor.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [279]:
X_test

array([[  28.66,   77.95, 1009.56,   69.07],
       [  17.48,   49.39, 1021.51,   84.53],
       [  14.86,   43.14, 1019.21,   99.14],
       ...,
       [  12.24,   44.92, 1023.74,   88.21],
       [  27.28,   47.93, 1003.46,   59.22],
       [  17.28,   39.99, 1007.09,   74.25]])

In [280]:
y_pred = regressor.predict(sc_x.fit_transform(X_test))
y_pred = sc_y.inverse_transform(y_pred.reshape(len(y_pred),1))


In [281]:
y_pred

array([[434.49984934],
       [457.70985097],
       [460.84909947],
       ...,
       [470.22304261],
       [439.28872637],
       [460.42910288]])

In [282]:
r2_score(y_test,y_pred)

0.9483693304317924